---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot6-0619
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot6-0619 
  name: chatbot6-0619
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi